// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hjxwyztqvsnvwstmgabf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhqeHd5enRxdnNudndzdG1nYWJmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzU2NDE1MjYsImV4cCI6MjA1MTIxNzUyNn0.RViOZXZEl9Ch24lUvPa4g04b4X5l0LIKAK3Sy5iSvnQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);